### ISSUE TITLE
Bug: All VST2 Windows versions crashing FL Studio 20

### ISSUE THREAD

**Issue by Flayzen** [mzuther/Squeezer#7] opened 2020-04-20 00:26 UTC
### Describe the bug

I am using Windows 10 and FL Studio 20. The VST2 versions all crash FL Studio very shortly after loading them into a project. The DAW will hang momentarily and then close down.

### Steps to reproduce

Simply load the plugin into an FL Studio project.

### Expected behavior

DAW crash.

### Environment (please complete the following information)

 - OS: [ Windows 10 (64-bit),]
 - DAW: [ FL Studio 20, 64 bit]
 - Plug-in: [ Squeezer v2.5.3 VST2 (64-bit)]

Did you compile Squeezer yourself? [no]

**Comment by mzuther** [comment] 2020-04-20 08:07
Thanks for your bug report!

I cannot reproduce your problem, though -- on my system, the VST2 plug-ins run just fine in FL Studio.

1. Did you copy the `squeezer` folder to the folder where you placed the plug-in DLLs?

2. What is your exact FL Studio version? Mine is 20.6 build 1458.

3. Maybe a crash report can help me.  You'll find them in the folder `Documents\Image-Line\Data\FL Studio\Support\Logs\Crash\`.

Martin

**Comment by cozytoaster773** [comment] 2020-05-12 01:45
I figured it out, I had the same issue. u have to drag the folder, not just the dll

**Comment by mzuther** [comment] 2020-05-12 08:22
Thanks @cozytoaster773! :smile: I have updated the manual (should anybody ever read that...) to make this absolutely clear.

@Flayzen Were you able to fix your problem?

**Comment by mzuther** [comment] 2020-11-16 22:13
Closing because it seems to have been solved (thus the silence). Feel free to re-open this bug report if the issue remains.

**Closed by mzuther** 2020-11-16 22:13 UTC
