### ISSUE TITLE
Bug: Squeezer parameters not persisted with FLStudio

### ISSUE THREAD

**Issue by Rondomat** [mzuther/Squeezer#15] opened 2021-03-22 19:23 UTC
### Describe the bug

Squeezer VST plugin (Stereo, VST3) does not persist the modified parameters. When opening the FLStdio project, the Squeezer parameters are not restored (or fall back to their defaults?).

### Steps to reproduce

1. [ start FLStudio ]
2. [ create a new song ]
3. [ open the mixer ]
5. [ add *Squeezer Stereo, no side-chain, VST3* to the track's first plug-in slot ]
6. [ modify some of the paramters like Trim, Output, Thresh, Ratio, etc. ]
7. [ save the FLStudio project ]
8. [ load the FLStudio project again ]
9. [ open the mixer ]
10. [ open Squeezer ]
11. [ the above mentioned parameters are not restored or might have been reset ]

### Expected behavior

The parameter values should restore to their last saved values when saving FLStudio project.
This works fine with other plugins.

### Environment (please complete the following information)

 - OS: [ Windows 10 (64-bit) ]
 - DAW: [ FLStudio v20.8.2 (64-bit) ]
 - Plug-in: [ Squeezer v2.5.3 VST3 (64-bit) ]

Did you compile Squeezer yourself? [no]

**Comment by mzuther** [comment] 2021-04-01 09:27
Thanks for your bug report!

I can reproduce the problem. This seems to be a common problem in FL Studio (but I don't want to blame them, maybe it's just a common bug in plug-ins): https://forum.image-line.com/viewtopic.php?f=200&t=219175

I have updated the library I use, but that didn't fix the problem. I currently don't have time to look into this, but you can use the VST2 version **without side-chain** which appears to work well.

*Note to self: https://forum.juce.com/t/fl-studio-20-vst-3-getstateinformation-called-when-plugin-is-being-created/32381*

**Comment by mzuther** [comment] 2024-07-14 00:24
I am sorry, but I have to close this issue because I simply do not have enough time to support this project.

**Closed by mzuther** 2024-07-14 00:24 UTC
